<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\TblBarrios;

class TblBarriosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        TblBarrios::insert([
            ['barrio' => 'BENJAMIN HERRERA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL TRONCAL',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'PARQUE DE LA CAÑA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'INDUSTRIAL',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LA BASE',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LAS AMERICAS',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'MUNICIPAL',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'URBANIZACION LA NUEVA BASE',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'VILLA COLOMBIA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'ASTURIAS',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'ATANACIO GIRARDOT',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'CHAPINERO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL RODEO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL TREBOL',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'FENALCO KENNEDY',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LA FLORESTA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'NUEVA FLORESTA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SANTA FE',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => '20 DE JULIO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'AGUABLANCA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'ALFONSO BARBERENA A.',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'BELLO HORIZONTE',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL PARAISO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL PRADO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL RECUERDO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'PRADOS DE ORIENTE',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'PRIMITIVO CRESPO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SAAVEDRA GALINDO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SAN BENITO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SANTA MONICA POPULAR',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SIMON BOLIVAR',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SIMON BOLIVAR (CALI)',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'URIBE URIBE',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'VILLANUEVA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EDUARDO SANTOS',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL JARDIN',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'JOSE MARIA CORDOBA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'JULIO RINCON',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LA ESPERANZA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LA FORTALEZA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LA GRAN COLOMBIA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LEON XIII',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LOS CONQUISTADORES',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'PRIMAVERA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SAN PEDRO CLAVER',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SINDICAL',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'URBANIZACION BOYACA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'JOSE HOLGUIN GARCES',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LA INDEPENDENCIA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LOS SAUCES - CIUDAD MODELO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LOS SAUCES',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'MARACAIBO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'VILLA DEL SUR',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL CALVARIO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL HOYO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LA MERCED',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'OBRERO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SAN JUAN BOSCO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SAN NICOLAS',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SAN PASCUAL',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SAN PEDRO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SANTA ROSA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SUCRE',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'ALAMEDA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'ARANJUEZ',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'BELALCAZAR',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'BRETAÑA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'GUAYAQUIL',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'JUNIN',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'MANUEL MARIA BUENAVENTURA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SANTA MONICA BELALCAZAR',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => '3 DE JULIO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'CHAMPAGNAT',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL CEDRO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EUCARISTICO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SAN FERNANDO NUEVO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'URBANIZACION COLSEGUROS',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'COLSEGUROS ANDES',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'CRISTOBAL COLON',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL DORADO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LA LIBERTAD',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LAS ACACIAS',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'OLIMPICO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SAN CRISTOBAL',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SANTA ELENA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'DEPARTAMENTAL',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LOS CAMBULOS',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'UNID. RES. SANTIAGO DE CALI',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'URBANIZACION MILITAR',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'URBANIZACION TEQUENDAMA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL GUABAL',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'JORGE ZAWADSKY',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LA SELVA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LAS GRANJAS',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'PANAMERICANO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'PASOANCHO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SAN JUDAS TADEO I',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SAN JUDAS TADEO II',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SANTO DOMINGO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'ASPROSOCIAL DIAMANTE',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'CALIPSO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'CHARCO AZUL',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'COMUNEROS II',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL POBLADO II',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL PONDAJE',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LLERAS - CINTA LARGA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LLERAS RESTREPO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LOS LAGOS',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LOS ROBLES',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'MARROQUIN III',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'OMAR TORRIJOS',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'RICARDO BALCAZAR',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'RODRIGO LARA BONILLA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SECTOR LAGUNA DEL PONDAJE',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SIETE DE AGOSTO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'ULPIANO LLOREDA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'VILLA DEL LAGO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'VILLABLANCA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'YIRA CASTRO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'ALIRIO MORA BELTRAN',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'JOSE M. MARROQUIN II E.',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LOS NARANJOS I',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LOS NARANJOS II',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'PROMOCIONES POPULARES',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'PUERTAS DEL SOL',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'PUERTO MALLARINO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'URB. EL ANGEL DEL HOGAR',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'ALFONSO BONILLA ARAGON',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'JOSE M. MARROQUIN I E.',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LAS ORQUIDEAS',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'MANUELA BELTRAN',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'MOJICA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'CIUDADELA DEL RIO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'COMPARTIR',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'INVICALI',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'TALANGA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'VALLE GRANDE',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'CALIMIO DESEPAZ',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL REMANSO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LOS LIDERES',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'PIZAMOS I',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'PIZAMOS II',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'PIZAMOS III',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'POTRERO GRANDE',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'VILLA MERCEDES',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'ANTONIO NARIÑO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL POBLADO I',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL RETIRO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL VERGEL',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LAUREANO GOMEZ',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LOS COMUNEROS I ETAPA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'VALLADO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL DIAMANTE',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LLERAS RESTREPO II',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'CIUDAD CORDOBA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL MORICHAL',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'MARIANO RAMOS',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'REPUBLICA DE ISRAEL',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'UNION VIVIENDA POPULAR',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'FONAVIEMCALI',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'JORGE ELIECER GAITAN',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LA RIVERA I',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LOS ALCAZARES',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'PETECUY PRIMERA ETAPA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'PETECUY SEGUNDA ETAPA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'PETECUY TERCERA ETAPA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SAN LUIS',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SAN LUIS II',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'URBANIZACION CALIMIO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'ALFONSO LOPEZ 1 ETAPA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'ALFONSO LOPEZ 2 ETAPA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'ALFONSO LOPEZ 3 ETAPA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'BASE AEREA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'FEPICOL',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LAS CEIBAS',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LOS PINOS',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SAN MARINO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LOS ANDES',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LOS ANDES B. - LA RIVIERA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LOS GUAYACANES',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LOS PARQUES - BARRANQUILLA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'METROPOLITANO DEL NORTE',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'PASEO DE LOS ALMENDROS',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'TORRES DE COMFANDI',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'VILLA DEL SOL',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'VILLA DEL SOL (CALI)',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'CHIMINANGOS PRIMERA ETAPA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'CHIMINANGOS SEGUNDA ETAPA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'JORGE ISAACS',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LA ALIANZA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LA ESMERALDA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LAS DELICIAS',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'MANZANARES',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'PORVENIR',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SALOMIA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SANTANDER',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SENA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'VILLA DEL PRADO EL GUABITO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LAS DELICIAS (CALI)',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'BRISAS DE LOS ALAMOS',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'CIUDADELA FLORALIA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LOS GUADUALES',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'PASO DEL COMERCIO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'PUENTE DEL COMERCIO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'CALIMA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'CIUDAD LOS ALAMOS',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'FLORA INDUSTRIAL',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'MENGA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'PARQUE DEL AMOR',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'URBANIZACION LA FLORA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'URBANIZACION LA MERCED',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'ALTOS DE MENGA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL BOSQUE',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LA CAMPIÑA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LA FLORA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LA PAZ',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'PRADOS DEL NORTE',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'VIPASA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'CENTENARIO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'CIUDAD CHIPICHAPE',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL PILOTO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'GRANADA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'JUANAMBU',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SAN VICENTE',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SANTA MONICA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'VERSALLES',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'BOLIVARIANO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'BUENO MADRID',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EVARISTO GARCIA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'FATIMA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'GUILLERMO VALENCIA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'IGNACIO RENGIFO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LA ISLA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'MARCO FIDEL SUAREZ',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'OLAYA HERRERA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'POPULAR',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SULTANA - BERLIN-SAN FRANCISCO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'AGUACATAL',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'ALTO BERLIN',    'id_mun' => 19,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'MEDIO BERLIN',    'id_mun' => 19,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'ALTO FUNDADORES',    'id_mun' => 19,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'ALTO SINAI',    'id_mun' => 19,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'BAJO BERLIN',    'id_mun' => 19,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'BAJO CAMPO ALEGRE',    'id_mun' => 19,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'MONTEBELLO',    'id_mun' => 89,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'BRISAS DE MONTEBELLO',    'id_mun' => 15,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'MONTEBELLO',    'id_mun' => 99,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'MONTEBELLO',    'id_mun' => 100,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'ARBOLEDAS',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'ARBOLEDA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'BELLAVISTA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL MAMEYAL',    'id_mun' => 90,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'VEREDA MAMEYAL',    'id_mun' => 91,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LA LEGUA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SECTOR PATIO BONITO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'TERRON COLORADO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'VISTA HERMOSA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'NORMANDIA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SANTA RITA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SANTA TERESITA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SECTOR BOSQUE MUNICIPAL',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'ACUEDUCTO SAN ANTONIO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL MORTIÑAL',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL NACIONAL',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL PEÑON',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LOS LIBERTADORES',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'MIRAFLORES',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'NAVARRO - LA CHANCA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SAN ANTONIO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SAN CAYETANO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SAN FERNANDO VIEJO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SANTA BARBARA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'TEJARES - CRISTALES',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'ALTOS DE SANTA ISABEL LA MORELIA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'BELEN',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'BELISARIO CAICEDO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'BRISAS DE MAYO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL CORTIJO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LA LUISA',    'id_mun' => 82,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LA REFORMA',    'id_mun' => 90,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LLERAS CAMARGO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'PARCELACIONES MONACO-LA SULTANA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'PUEBLO JOVEN',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SECTOR CAÑAVERALEJO GUADALUPE',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SILOE',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'TIERRA BLANCA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'VENEZUELA URB. CAÑAVERALEJO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'CUARTO DE LEGUA - GUADALUPE',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL LIDO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SANTA ISABEL',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'U. R. EL COLISEO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'URBANIZACION NUEVA GRANADA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'FATIMA (CALI)',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'NUEVA TEQUENDAMA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'ALFEREZ REAL',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'ALTO NAPOLES',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'BUENOS AIRES',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'CALDAS',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'COLINAS DEL SUR',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL REFUGIO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'FRANCISCO ELADIO RAMIREZ',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LA CASCADA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LOS CHORROS',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LOS FARALLONES',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LOURDES',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'MARIO CORREA RENGIFO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'NAPOLES',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'PAMPA LINDA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'PRADOS DEL SUR',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SECTOR ALTO DE LOS CHORROS',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'BOSQUE DEL LIMONAR',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'CAMINO REAL - JOAQUIN BORRERO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'CAMINO REAL LOS FUNDADORES',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'CAÑAVERALEJO - SEGUROS PATRIA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'CAÑAVERALES LOS SAMANES',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL GRAN LIMONAR',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL GRAN LIMONAR - CATAYA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL LIMONAR',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'PRIMERO DE MAYO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SANTA ANITA - LA SELVA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'CUARTELES NAPOLES',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL JORDAN',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'HORIZONTES',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'MELENDEZ',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'POLVORINES',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SECTOR ALTO JORDAN',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SECTOR MELENDEZ',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'CIUDAD CAPRI',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'CIUDAD UNIVERSITARIA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'CIUDADELA PASOANCHO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL INGENIO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LA PLAYA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LAS QUINTAS DE DON SIMON',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'MAYAPAN - LAS VEGAS',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'PRADOS DEL LIMONAR',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SAN JOAQUIN',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'UNICENTRO CALI',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'BRISAS DEL LIMONAR',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'CIUDAD 2000',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'CIUDADELA COMFANDI',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL CANEY',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LA ALBORADA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LAS VEGAS DE COMFANDI',    'id_mun' => 103,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'URBANIZACION LILI',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SECTOR LA VIGA',    'id_mun' => 109,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'VEREDA PALERMO',    'id_mun' => 103,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'BOCHALEMA',    'id_mun' => 22,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'BOCHALEMA',    'id_mun' => 48,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'CIUDAD CAMPESTRE',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'CLUB CAMPESTRE',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL PORTENTO',    'id_mun' => 51,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LA BUITRERA',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LA RIVERITA',    'id_mun' => 73,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LOS CERROS',    'id_mun' => 92,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'PUEBLO NUEVO',    'id_mun' => 120,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SECTOR ANCHICAYA',    'id_mun' => 120,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SECTOR ANDALUCIA',    'id_mun' => 48,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'URBANIZACION CIUDAD JARDIN',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'URBANIZACION RIO LILI',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'CASCAJAL 1',    'id_mun' => 22,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'CASCAJAL 2',    'id_mun' => 23,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL HORMIGUERO',    'id_mun' => 23,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'PARCELACIONES PANCE',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'PIZAMOS',    'id_mun' => 48,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'VILLA FLAMENCO',   'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'BELLAVISTA',    'id_mun' => 163,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'DIONISIO HERNAN CALDERON',    'id_mun' => 163,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'EL MADRIGAL',    'id_mun' => 163,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'FLORAL',    'id_mun' => 163,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'FRAY PEÑA',    'id_mun' => 163,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'GUACANDA',    'id_mun' => 163,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LA CEIBA',    'id_mun' => 163,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LLERAS',    'id_mun' => 163,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'MUNICIPAL',    'id_mun' => 163,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'NUEVO HORIZONTE',    'id_mun' => 163,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'PEDREGAL',    'id_mun' => 163,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'TRINIDAD',    'id_mun' => 163,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'TRINIDAD I',    'id_mun' => 163,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'VEGAS',    'id_mun' => 163,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'BELALCAZAR',    'id_mun' => 163,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'JORGE ELIECER',    'id_mun' => 163,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'JUAN PABLO II',    'id_mun' => 163,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'PORTALES DE YUMBO',    'id_mun' => 163,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SAN FERNANDO',    'id_mun' => 163,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'URB. CARLOS PIZARRO',    'id_mun' => 163,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'URB. NUESTRA SRA DE GUADALUPE',    'id_mun' => 163,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'ASOVIVIR LAS COLINAS',    'id_mun' => 163,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'BOLIVAR',    'id_mun' => 163,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'BUENOS AIRES',    'id_mun' => 163,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'CORVIVALLE',    'id_mun' => 163,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LA ESTANCIA',    'id_mun' => 163,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LA NUEVA ESTANCIA',    'id_mun' => 163,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'PORTALES DE COMFANDI',    'id_mun' => 163,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'URIBE',    'id_mun' => 163,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'ALTO SAN JORGE',    'id_mun' => 163,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'CRUCES',    'id_mun' => 163,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'INVIYUMBO SAN JORGE',    'id_mun' => 163,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'LAS AMERICAS',    'id_mun' => 163,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'PANORAMA',    'id_mun' => 163,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'PUERTO ISAAC',    'id_mun' => 163,    'created_at' => now(), 'updated_at' => now()],
            ['barrio' => 'SAN JORGE',    'id_mun' => 163,    'created_at' => now(), 'updated_at' => now()]
        ]);
    }
}
